name: Build xLua Lua54 (All Platforms)

on:
  push:
    paths:
      - build/**
      - .github/workflows/build-all-platforms.yml
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: Build
        run: |
          export ANDROID_NDK=~/android-ndk-r21e
          cd build && ./make_android_lua54.sh
      - uses: actions/upload-artifact@v4
        with:
          name: plugin_lua54_android
          path: ./build/plugin_lua54/**/*

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd build && ./make_linux_lua54.sh
      - uses: actions/upload-artifact@v4
        with:
          name: plugin_lua54_linux
          path: ./build/plugin_lua54/**/*

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd build && ./make_ios_lua54.sh
      - uses: actions/upload-artifact@v4
        with:
          name: plugin_lua54_ios
          path: ./build/plugin_lua54/**/*

  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd build && ./make_osx_lua54.sh
      - uses: actions/upload-artifact@v4
        with:
          name: plugin_lua54_osx
          path: ./build/plugin_lua54/**/*

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        run: |
          cd build
          .\make_win_lua54.bat
      - uses: actions/upload-artifact@v4
        with:
          name: plugin_lua54_windows
          path: ./build/plugin_lua54/**/*
